# Generated by Django 2.2.24 on 2023-02-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemonentity_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='author',
            new_name='Pokemon',
        ),
    ]
