# Generated by Django 2.2.24 on 2023-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20230212_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='Appeared at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='Desappeared at',
            field=models.DateTimeField(null=True),
        ),
    ]
