# Generated by Django 2.2.24 on 2023-02-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20230212_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Appeared at',
            new_name='Appeared',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Desappeared at',
            new_name='Desappeared',
        ),
    ]
