# Generated by Django 2.2.24 on 2023-02-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0019_auto_20230212_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='Appeared',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Появился в'),
        ),
    ]
