# Generated by Django 2.2.24 on 2023-02-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0025_auto_20230214_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='Pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='pokemon_entities.Pokemon', verbose_name='Покемон'),
        ),
    ]
